global:
  openai:
    base_url: "https://api.siliconflow.cn/v1"
  response:
    url: "https://api.siliconflow.cn/v1/chat/completions"
  api_key: "your_api_key"
  model_for_clean: "Qwen/Qwen2.5-32B-Instruct"
  model_for_summary: "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B"
  